### ISSUE TITLE
Please add me to initial developer list, ID 185

### ISSUE THREAD

**Issue by adam-paterson** [tzyganu/WhoIsOnMageOverflow#2]

**Comment by tzyganu** [comment]
@adam-paterson I see that you have only 3 answers posted (from which 1 is deleted) and one question. And a total score of 54. There is no official limit for adding someone in the initial dataset but I think 54 is not that much.  
Don't take this the wrong way, there is nothing personal, but I think 54 points is not that much in almost 2 years.  
Ping me again when you get over (let's say) 400 points.  
I will add this arbitrary limit to the readme file.

**Comment by adam-paterson** [comment]
@tzyganu Okay, no problem.
